[CI] setup MariaDB in symfony tests.

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -107,5 +107,26 @@ jobs:
     - name: Run twig template lint
       run: ./bin/console lint:twig templates --env=prod
 
+    - name: Setup MariaDb
+      uses: getong/mariadb-action@v1.1
+      with:
+        #host port: 3800 # Optional, default value is 3306. The port of host
+        #container port: 3307 # Optional, default value is 3306. The port of container
+        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
+        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
+        mariadb version: '10.3.29' # Optional, default value is "latest". The version of the MariaDB
+        mysql database: 'symfony_test' # Optional, default value is "test". The specified database which will be create
+        #mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
+        mysql user: 'test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
+        mysql password: 'test' #${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
+
+    - name: Run Migration
+      run: |
+        php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+        php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+      env:
+        DATABASE_URL: mysql://test:test@127.0.0.1:3306/symfony
+
+
     - name: Run test suite
       run: bin/phpunit
